In [70]:
import pandas as pd
import numpy as np

In [71]:
data=pd.read_excel("回归数据.xlsx")
data=data[["证券名称","总资产(元)"]]
for i in range(len(data)):
    if data["总资产(元)"][i]=='——':
        data["总资产(元)"][i]=data["总资产(元)"][i-1]

In [72]:
names=[]
for i in data.drop_duplicates(subset='证券名称', keep='first', inplace=False)["证券名称"]:
    names.append(i)

In [73]:
meandata={}
for i in names:
    meandata[i]=data[data["证券名称"]==i]["总资产(元)"].mean()

In [74]:
weightdata={}
for i in meandata:
    weightdata[i]=meandata[i]/sum(meandata.values())

In [75]:
returndata=pd.read_excel("收益率.xlsx")

In [76]:
renames=names

In [77]:
renames.insert(0,"rm")

In [78]:
renames.insert(0,"time")

In [79]:
returndata_rename=returndata

In [80]:
returndata_rename.columns=renames

In [81]:
rm=[]
for j in range(len(returndata_rename)):
    a={}
    for i in weightdata:
        a[i]=weightdata[i]*returndata_rename[i][j]
    rm.append(sum(a.values()))

In [82]:
returndata_rename["rm"]=rm

In [87]:
returndata_rename

,time,rm,万科A,ST国华,ST星源,深振业A,*ST全新,神州高铁,中国宝安,深物业A,...,平煤股份,潞安环能,中海油服,中国石油,中远海发,招商轮船,新集能源,中远海控,大唐发电,出版传媒
0,2008-01-02,0.803503,0.523884,1.877400,0.546290,0.887688,1.308386,0.417929,0.190779,1.050627,...,-0.498708,-0.769223,0.000000,-0.536347,0.000000,0.603196,0.163371,2.713065,0.000000,2.984877
1,2008-01-03,0.612735,-1.054165,1.153791,1.598811,-0.293885,2.078884,-0.104106,-0.657619,0.927590,...,0.103977,-1.116756,2.278829,0.704353,-0.902932,1.052090,-0.464491,0.485038,0.000000,-0.544261
2,2008-01-04,0.292065,1.128492,0.565601,-0.526424,2.063507,-0.053452,2.135471,0.027601,0.130910,...,0.441484,0.863487,0.203529,0.320206,0.580035,-0.489995,0.464491,2.131538,0.000000,0.363598
3,2008-01-07,0.556617,1.374187,1.421454,1.218541,1.745373,2.139300,-0.801181,-1.004839,-0.163700,...,1.587437,4.060347,0.000000,-0.306235,1.102239,0.392437,1.835882,-0.717258,0.000000,0.260718
4,2008-01-08,-0.702735,-0.433864,-0.744411,-1.159734,-1.248321,-0.153011,-1.091764,-1.377007,-2.082863,...,-1.373016,-1.597612,-0.892996,-0.153931,-1.791898,-1.021141,-1.781562,0.337406,0.000000,2.937630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,2021-12-27,0.174558,-0.044248,-0.551492,0.386042,0.492962,-0.667588,-3.728908,-0.589619,-0.259060,...,-0.301944,-0.407443,-0.235550,0.087825,0.000000,0.106314,0.090762,0.796893,-0.509442,-0.466629
3401,2021-12-28,-0.215826,0.132609,1.678423,0.572704,-0.492962,-0.678010,-2.782909,1.080006,-0.485250,...,-1.699294,-1.399241,0.847859,-0.175828,0.395415,0.000000,-1.757768,2.041446,-1.831634,0.267259
3402,2021-12-29,-0.218549,-0.667132,-0.290200,0.000000,0.099041,0.377978,-1.461316,0.060911,-0.339147,...,0.470077,0.115147,0.000000,-0.176543,-0.263210,-0.212890,0.562809,-0.333647,-1.357281,-0.738957
3403,2021-12-30,0.138935,-0.586588,0.467826,0.000000,-0.099041,1.041167,1.937695,-0.274774,-0.075727,...,-0.104023,-0.346360,-0.700490,-0.088541,-0.397830,0.106575,-0.562809,-1.707800,0.683942,4.133109
3404,2021-12-31,0.372867,1.429905,-0.400685,0.189235,0.786075,1.302981,2.901464,0.759010,0.751393,...,0.155941,0.269629,0.700490,0.088541,-0.133424,0.212369,-0.570198,-0.023231,0.539503,-0.309108

In [86]:
returndata_rename.to_excel("算MES数据.xlsx",index = False)